//
//  StudentLocation.swift
//  OnTheMap
//
//  Created by LALIT JAGTAP on 4/14/20.
//  Copyright © 2020 LALIT JAGTAP. All rights reserved.
//

import Foundation

public struct StudentLocations: Codable {
    public let results: [StudentInformation]
}

    // uniqueKey - populate this using your Udacity Account id
    // Do no worry about parsing Date and ObjectID
    // objectID - auto generated by PARSE not needed

public struct StudentInformation: Codable {
    let firstName, lastName: String
    let longitude, latitude: Double
    let mapString: String
    let mediaURL: String
    let uniqueKey, objectID, createdAt, updatedAt: String

    enum CodingKeys: String, CodingKey {
        case firstName, lastName, longitude, latitude, mapString, mediaURL, uniqueKey
        case objectID = "objectId"
        case createdAt, updatedAt
    }
}



/*
 
 To get multiple student locations at one time, you'll want to use the following API method:
 
 GET https://onthemap-api.udacity.com/v1/StudentLocation
 
 Optional Parameters:

 limit - (Number) specifies the maximum number of StudentLocation objects to return in the JSON response
    https://onthemap-api.udacity.com/v1/StudentLocation?limit=100
 
 skip - (Number) use this parameter with limit to paginate through results
    https://onthemap-api.udacity.com/v1/StudentLocation?limit=200&skip=400
 
 order - (String) a comma-separate list of key names that specify the sorted order of the results
    Prefixing a key name with a negative sign reverses the order (default order is ascending)
    https://onthemap-api.udacity.com/v1/StudentLocation?order=-updatedAt
 
 uniqueKey - (String) a unique key (user ID). Gets only student locations with a given user ID.
    Filtering by the user ID can be useful if the user has already posted a location
    https://onthemap-api.udacity.com/v1/StudentLocation?uniqueKey=1234
 
 
 Example data
 http://video.udacity-data.com.s3.amazonaws.com/topher/2016/June/57583b20_get-student-locations/get-student-locations.json
 
 
 GET /v1/StudentLocation HTTP/1.1
 Host: onthemap-api.udacity.com
 cache-control: no-cache
 Postman-Token: dc7475c8-8341-436e-810f-c806623b7983
 
 {"results":
 [{"firstName":"Markus",
 "lastName":"Suzuki",
 "longitude":-97.747505,
 "latitude":30.264265,
 "mapString":"Austin, TX",
 "mediaURL":"https://www.udacity.com",
 "uniqueKey":"1234",
 "objectId":"ID10",
 "createdAt":"2019-05-17T00:53:33.941Z",
 "updatedAt":"2020-04-13T15:38:23.867Z"},

 {"firstName":"",
 "lastName":"",
 "longitude":-8.6869335,
 "latitude":39.23924,
 "mapString":"Santarém",
 "mediaURL":"https://",
 "uniqueKey":"92232372",
 "objectId":"bji6d8rcspggujsjjd10",
 "createdAt":"2019-05-21T20:59:15.161Z",
 "updatedAt":"2020-03-26T22:40:37.329Z"}]
 }
 */


